// Centralized UI text. All UI text is in English.
window.STRINGS = {
  churchName: 'Kebena MKC',
  churchNameEn: 'Kebena MKC',

  nav: {
    home: 'Home',
    homeEn: 'Home',
    lyrics: 'Song Lyrics',
    lyricsEn: 'Song Lyrics',
    notices: 'Notices',
    noticesEn: 'Notices',
    bank: 'Bank Accounts',
    bankEn: 'Bank Accounts',
    bible: 'Bible',
    bibleEn: 'Bible',
    slides: 'Slideshow',
    slidesEn: 'Slideshow',
    media: 'Video',
    mediaEn: 'Video',
    countdown: 'Countdown',
    countdownEn: 'Countdown',
    social: 'Social Media',
    socialEn: 'Social Media',
    playlists: 'Playlists',
    playlistsEn: 'Playlists',
    bibleSync: 'Online Bible',
    bibleSyncEn: 'Online Bible',
    settings: 'Settings',
    settingsEn: 'Settings'
  },

  common: {
    add: 'Add',
    save: 'Save',
    saveEn: 'Save',
    edit: 'Edit',
    editEn: 'Edit',
    delete: 'Delete',
    deleteEn: 'Delete',
    cancel: 'Cancel',
    cancelEn: 'Cancel',
    present: 'Present',
    presentEn: 'Present',
    next: 'Next',
    prev: 'Previous',
    exit: 'Exit',
    back: 'Back',
    confirmDelete: 'Are you sure you want to delete this record?',
    empty: 'Nothing added yet'
  },

  // Controls for the operator's local preview of what the audience screen is
  // showing. "Minimize" hides only the preview; the second screen keeps going.
  present: {
    presentingLive: 'Live on the second screen',
    presentingLiveEn: 'Live on the second screen',
    showPreview: 'Show preview',
    showPreviewEn: 'Show preview',
    minimizePreview: 'Minimize preview (Ctrl+M)',
    minimizePreviewEn: 'Minimize preview (Ctrl+M)',
    exitPresentation: 'Exit presentation (Esc)',
    exitPresentationEn: 'Exit presentation (Esc)'
  },

  lyrics: {
    title: 'Song Lyrics',
    titleEn: 'Song Lyrics',
    importDocx: 'Import File (.docx)',
    importDocxEn: 'Import File (.docx)',
    newSong: 'New Song',
    newSongEn: 'New Song',
    importing: 'Reading file...',
    songTitleLabel: 'Song Title',
    reviewTitle: 'Review the Lyrics',
    reviewHint: 'Please read the text carefully before presenting. Fix any typos if needed.',
    looksGoodSave: 'Looks Good, Save',
    noSlides: 'No lyrics found. Please check the file.',
    slideOf: '{current} / {total}',
    autoAdvance: 'Auto',
    manual: 'Manual',
    edit: 'Edit',
    editSong: 'Edit Song',
    lyricsLabel: 'Lyrics',
    editHint: 'A blank line (two spaces) starts a new verse.'
  },

  notices: {
    title: 'Weekly Notices',
    titleEn: 'Weekly Notices',
    addNotice: 'Add Notice',
    addNoticeEn: 'Add Notice',
    noticeTitleLabel: 'Title',
    dateLabel: 'Date',
    timeLabel: 'Time',
    bodyLabel: 'Content',
    bodyHint: 'Wrap important words with **like this** to highlight them',
    titleRequired: 'Please enter a title',
    noDate: 'No date',
    empty: 'No notices added yet',
    noticeTypeLabel: 'Notice Type',
    newShort: 'New',
    permanentShort: 'Regular',
    new: 'New',
    permanent: 'Regular',
    hideFromPresent: 'Hide from list',
    showInPresent: 'Show in list'
  },

  creed: {
    title: "Apostles' Creed",
    titleEn: "Apostles' Creed"
  },

  bible: {
    title: 'Bible',
    titleEn: 'Bible',
    book: 'Book',
    chapter: 'Chapter',
    verses: 'Verses',
    verseTo: 'To',
    oldTestament: 'Old Testament',
    newTestament: 'New Testament',
    selectRange: 'To',
    clearSelection: 'Clear Selection',
    reload: 'Retry',
    noData: 'Bible data not found',
    noDataHint: 'Bible text must be stored in the data/bible.json file. Download the complete Amharic Bible JSON from github.com/magna25/amharic-bible-json and replace this file.'
  },

  bibleSync: {
    title: 'Online Bible',
    titleEn: 'Online Bible',
    versionLabel: 'Version:',
    versionLabelEn: 'Version:',
    downloadBook: 'Download Book',
    downloadBookEn: 'Download Book',
    checkUpdates: 'Check for Updates',
    checkUpdatesEn: 'Check for Updates',
    availableBooks: 'Available Books (Local)',
    availableBooksEn: 'Available Books (Local)',
    downloading: 'Downloading...',
    downloadingEn: 'Downloading...',
    update: 'Update',
    updateEn: 'Update'
  },

  calendar: {
    label: 'Calendar',
    gregorian: 'Gregorian',
    ethiopian: 'Ethiopian',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    equals: 'Equals',
    ethMonths: ['Meskerem', 'Tikimt', 'Hidar', 'Tahsas', 'Tir', 'Yekatit', 'Megabit', 'Miazia', 'Ginbot', 'Sene', 'Hamle', 'Nehase', 'Pagume'],
    gcMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },

  bank: {
    title: 'Bank Accounts',
    titleEn: 'Bank Accounts',
    addAccount: 'Add Account',
    addAccountEn: 'Add Account',
    bankNameLabel: 'Bank Name',
    bankNameLabelEn: 'Bank Name',
    accountNumberLabel: 'Account Number',
    accountNumberLabelEn: 'Account Number',
    holderNameLabel: 'Account Holder Name',
    holderNameLabelEn: 'Account Holder Name',
    iconLabel: 'Logo',
    iconLabelEn: 'Logo',
    empty: 'No accounts added yet',
    emptyEn: 'No accounts added yet',
    spotlightBadge: 'Spotlight View',
    scanToPay: 'Scan to Pay'
  },

  slides: {
    title: 'Slideshow',
    titleEn: 'Slideshow',
    addImages: 'Add Images',
    addImagesEn: 'Add Images',
    empty: 'No images added yet',
    durationLabel: 'Image Duration (seconds)',
    present: 'Start Slideshow',
    presentEn: 'Start Slideshow',
    noImages: 'Please add at least one image'
  },

  media: {
    title: 'Media / Video',
    titleEn: 'Media / Video',
    addLink: 'Add YouTube Link',
    addLinkEn: 'Add YouTube Link',
    urlLabel: 'YouTube URL',
    urlLabelEn: 'YouTube URL',
    urlHint: 'Enter a full URL or video ID',
    empty: 'No links added yet',
    play: 'Play',
    titleLabel: 'Title (optional)',
    titleLabelEn: 'Title (optional)'
  },

  countdown: {
    title: 'Countdown Timer',
    titleEn: 'Countdown Timer',
    addPreset: 'Add Countdown',
    addPresetEn: 'Add Countdown',
    modeLabel: 'Timer mode',
    modeLabelEn: 'Timer mode',
    modeDuration: 'Duration',
    modeDurationEn: 'Duration',
    modeTarget: 'Target time',
    modeTargetEn: 'Target time',
    hoursLabel: 'Hours',
    hoursLabelEn: 'Hours',
    minutesLabel: 'Minutes',
    minutesLabelEn: 'Minutes',
    secondsLabel: 'Seconds',
    secondsLabelEn: 'Seconds',
    titleLabel: 'Title',
    titleLabelEn: 'Title',
    empty: 'No countdowns added yet',
    start: 'Start',
    startEn: 'Start',
    reset: 'Reset',
    resetEn: 'Reset',
    completed: 'Time is up!',
    completedEn: 'Time is up!',
    showEthiopianTime: 'Show Ethiopian Time',
    targetDateLabel: 'Target date',
    targetDateLabelEn: 'Target date',
    targetTimeLabel: 'Target time',
    targetTimeLabelEn: 'Target time'
  },

  social: {
    title: 'Social Media',
    titleEn: 'Social Media',
    addAccount: 'Add Social Media',
    addAccountEn: 'Add Social Media',
    platformLabel: 'Platform',
    platformLabelEn: 'Platform',
    usernameLabel: 'Username (@)',
    usernameLabelEn: 'Username (@)',
    urlLabel: 'URL',
    urlLabelEn: 'URL',
    empty: 'No social media added yet',
    followUs: 'Follow Us',
    scanToFollow: 'Scan to Follow',
    present: 'Present',
    presentEn: 'Present'
  },

  bibleQuotes: {
    title: 'Bible Quotes',
    titleEn: 'Bible Quotes',
    addQuote: 'Add Quote',
    addQuoteEn: 'Add Quote',
    editQuote: 'Edit Quote',
    editQuoteEn: 'Edit Quote',
    quoteText: 'Bible Quote',
    quoteTextEn: 'Bible Quote',
    reference: 'Reference',
    referenceEn: 'Reference',
    quoteHint: 'Enter the Bible verse text here...',
    quoteHintEn: 'Enter the Bible verse text here...',
    refHint: 'e.g. John 3:16',
    refHintEn: 'e.g. John 3:16',
    quoteRequired: 'Please enter a Bible quote',
    quoteRequiredEn: 'Please enter a Bible quote',
    empty: 'No quotes added yet',
    emptyEn: 'No quotes added yet',
    edit: 'Edit',
    editEn: 'Edit',
    delete: 'Delete',
    deleteEn: 'Delete',
    save: 'Save',
    saveEn: 'Save',
    cancel: 'Cancel',
    cancelEn: 'Cancel',
    present: 'Present',
    presentEn: 'Present'
  },

  settings: {
    title: 'Settings',
    titleEn: 'Settings',
    subtitleEn: 'Configure how lyrics, notices, and media are displayed.',
    autoAdvanceSeconds: 'Auto-advance lyrics (seconds)',
    autoAdvanceSecondsEn: 'Auto-advance lyrics (seconds)',
    autoAdvanceHintEn: 'Seconds before the next verse is shown automatically.',
    lyricsAnimation: 'Lyrics animation style',
    lyricsAnimationEn: 'Lyrics animation style',
    lyricsAnimationHintEn: 'Transition style between verses.',
    fade: 'Fade',
    fadeEn: 'Fade',
    lineByLine: 'Line by line',
    lineByLineEn: 'Line by line',
    noticeRotateSeconds: 'Notice rotation interval (seconds)',
    noticeRotateSecondsEn: 'Notice rotation interval (seconds)',
    noticeRotateHintEn: 'Seconds each notice group stays on screen.',
    noticesPerSlide: 'Notices per slide',
    noticesPerSlideEn: 'Notices per slide',
    noticesPerSlideHintEn: 'Number of notices shown together per slide.',
    "churchName": 'Church name',
    churchNameEn: 'Church name',
    churchNameHintEn: 'Appears in the header and presentation screen.',
    "slideDurationSeconds": 'Social media slide duration (seconds)',
    slideDurationSecondsEn: 'Social media slide duration (seconds)',
    slideDurationHintEn: 'Seconds each social post stays on screen.',
    "lyricsFontSize": 'Lyrics font size (pt)',
    lyricsFontSizeEn: 'Lyrics font size (pt)',
    lyricsFontSizeHintEn: 'Base text size in points.',
    "fontFamily": 'Font family',
    fontFamilyEn: 'Font family',
    fontFamilyHintEn: 'Default font for lyrics and notices.',
    "lyricsIdleAnimation": 'Idle screen animation',
    lyricsIdleAnimationEn: 'Idle screen animation',
    lyricsIdleHintEn: 'Background animation when no lyrics are showing.',
    "idleAnimSoundwave": 'Sound Wave',
    idleAnimSoundwaveEn: 'Sound Wave',
    "idleAnimCircularWave": 'Circular Equalizer',
    idleAnimCircularWaveEn: 'Circular Equalizer',
    "idleAnimGlowWave": 'Glow Waveform',
    idleAnimGlowWaveEn: 'Glow Waveform',
    "idleAnimPulseCross": 'Pulsing Cross',
    idleAnimPulseCrossEn: 'Pulsing Cross',
    "idleAnimFloatingDots": 'Floating Dots',
    idleAnimFloatingDotsEn: 'Floating Dots',
    "idleAnimRipple": 'Ripple Circles',
    idleAnimRippleEn: 'Ripple Circles',
    "idleAnimBreathingGlow": 'Breathing Glow',
    idleAnimBreathingGlowEn: 'Breathing Glow',
    "idleAnimNone": 'None / Blank',
    idleAnimNoneEn: 'None / Blank',
    sectionChurchEn: 'Church',
    sectionChurchDescEn: 'Identity shown across the app and on the display.',
    sectionLyricsEn: 'Lyrics',
    sectionLyricsDescEn: 'How song lyrics appear on the display.',
    sectionNoticesEn: 'Notices',
    sectionNoticesDescEn: 'How announcements cycle on the display.',
    sectionSocialEn: 'Social Media',
    sectionSocialDescEn: 'Timing for social media slideshows.',
    sectionBibleEn: 'Bible Content Update',
    sectionBibleDescEn: 'Browse and edit book, chapter, and verse content.',
    footerHintEn: 'Changes apply to the next presentation.'
  }
};